#!/bin/bash

# Periksa apakah ini adalah commit pertama
if [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" != "true" ]; then
  echo "Error: Not inside a git repository."
  exit 1
fi

if [ -z "$(git rev-parse --verify HEAD 2>/dev/null)" ]; then
  echo "Info: First commit, skipping branch and staged files checks."
  exit 0
fi

# Ambil nama branch saat ini
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Tentukan branch yang dilindungi
protected_branches=("main" "develop")

# Periksa apakah branch saat ini termasuk branch yang dilindungi
for protected_branch in "${protected_branches[@]}"; do
  if [[ "$branch_name" == "$protected_branch" ]]; then
    echo -e "\e[31mDirect commits to $branch_name branch are not allowed. Please create a new branch, then send a pull request.\e[0m"
    exit 1
  fi
done

exit 0
